mode: "train"  # or "evaluate"
model_selection: "i3d"
model:
  num_classes: 10
hyperparameters:
  learning_rate: 0.001
  batch_size: 32
  num_epochs: 50
  weight_decay: 0.0001
  dropout_rate: 0.5
data:
  train_data_path: "path/to/train/data"
  val_data_path: "path/to/val/data"
  test_data_path: "path/to/test/data"
augmentation:
  use_augmentation: true
  augmentations:
    - type: "random_crop"
      size: [224, 224]
    - type: "random_flip"
      horizontal: true
    - type: "normalize"
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]