mode: "train"  # or "evaluate"
dataset: "visl2"        # dataset key used by DatasetRegistry (e.g. visl2_dataset.py defines Visl2Dataset)
model_selection: "i3d"
model:
  num_classes: 10
hyperparameters:
  learning_rate: 0.001
  batch_size: 32
  num_epochs: 50
  weight_decay: 0.0001
  dropout_rate: 0.5
data:
  train_data_path: "path/to/train/data"
  val_data_path: "path/to/val/data"
  test_data_path: "path/to/test/data"
  output: "rgb"         # for selecting the output type (rgb, rgbd, flow)
augmentation:
  use_augmentation: true
  augmentations:
    - type: "random_crop"
      size: [224, 224]
      scale: [0.8, 1.0]
    - type: "random_flip"
      horizontal: true
      vertical: false
    - type: "color_jitter"
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    - type: "normalize"
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]