mode: "train"

dataset:
  name: "czech_slr"
  paths:
    train_data_path: "path/to/czech_train.csv"
    val_data_path: "path/to/czech_val.csv"
    test_data_path: "path/to/czech_test.csv"
  batch_size: 32
  num_frames: 32
  output: "skeleton"
  cache_folder: "path/to/cache/"
  augmentation:
    use_augmentation: true
    augmentations:
      temporal:
        frame_skip_range: [1, 3]
        frame_duplicate_prob: 0.2
        temporal_crop_scale: [0.8, 1.0]
        min_frames: 32
      spatial:
        rotation_range: [-13, 13]
        squeeze_range: [0, 0.15]
        perspective_ratio_range: [0, 1]
        joint_rotation_prob: 0.3
        joint_rotation_range: [-4, 4]

model:
  model_name: "spoter"
  num_classes: 157  
  hidden_dim: 128  

hyperparameters:
  learning_rate: 0.001
  weight_decay: 0.0001
  num_epochs: 100
  batch_size: 32
  dropout_rate: 0.5

device: "cuda"