

mode: "train"

dataset:
  'train':
    phase: 'train'
    name: 'RgbOnlyDataset'
    root_dir: '/work/21013187/SignLanguageRGBD/data/ver2_all_rgb_only'
    
    image_size: 80
    loader_config: 
      batch_size: 128
      shuffle: true
      # num_workers: 1
      drop_last: true

  'val':
    name: 'RgbOnlyDataset'
    phase: 'test'
    image_size: 80
    loader_config: 
      batch_size: 64
      shuffle: true
      drop_last: true


model:
  model_name: "i3d"
  num_classes: 10

hyperparameters:
  learning_rate: 0.001
  batch_size: 32
  num_epochs: 50
  weight_decay: 0.0001
  dropout_rate: 0.5