

mode: "train"

dataset:
  name: 'RgbOnly'
  'train':
    
    root_dir: '/work/21013187/SignLanguageRGBD/data/ver2_all_rgb_only'
    num_frames: 36
    img_size: 224

    dataloader_config: 
      
      batch_size: 12
      shuffle: true
      drop_last: true

  'val':
    root_dir: '/work/21013187/SignLanguageRGBD/data/ver2_all_rgb_only'
    num_frames: 36
    img_size: 224

    dataloader_config: 
      batch_size: 12
      drop_last: true
     

  'test':
    root_dir: '/work/21013187/SignLanguageRGBD/data/ver2_all_rgb_only'
    num_frames: 36
    img_size: 224
    
    dataloader_config: 
      batch_size: 12
      drop_last: true


model:
  model_name: "i3d"
  num_classes: 200

optimizer_config:
  lr: 0.0001


hyperparameters:
  num_epochs: 100