mode: "train"

dataset:
  name: "visl2"
  height: 224
  width: 224
  n_frames: 32
  batch_size: 32
  num_classes: 100  
  output: "skeleton"
  cache_folder: "/work/21010294/ViSL-2/cache/"
  person_selection:
    train:
      mode: "index"
      indices: [ [6,30] ]
    val:
      mode: "index"
      indices: [ [4,5] ]
    test:
      mode: "index"
      indices: [ [1,3] ]
  augmentation:
    use_augmentation: true
    augmentations:
      temporal:
        frame_skip_range: [1, 3]
        frame_duplicate_prob: 0.2
        temporal_crop_scale: [0.8, 1.0]
        min_frames: 32
      spatial:
        rotation_range: [-13, 13]
        squeeze_range: [0, 0.15]
        perspective_ratio_range: [0, 1]
        joint_rotation_prob: 0.3
        joint_rotation_range: [-4, 4]
  paths:
    train_data_path: "/work/21010294/ViSL-2/Processed"
    val_data_path: "/work/21010294/ViSL-2/Processed"
    test_data_path: "/work/21010294/ViSL-2/Processed"

model:
  model_name: "spoter"
  hidden_dim: 256  # Must be divisible by num_heads
  num_heads: 8
  num_encoder_layers: 6
  num_decoder_layers: 6
  dim_feedforward: 2048
  dropout: 0.1

hyperparameters:
  learning_rate: 0.001
  weight_decay: 0.0001
  num_epochs: 100
  batch_size: 32
  dropout_rate: 0.5

device: "cuda"